Update vs-buildtools
airpwr/shipyard pull request #47
Opened 2022-10-26 23:22 UTC by nicklauslittle

This should allow automatic, rolling updates for each LTSC release. (At least, for VS 2022. Probably changes will be needed to support later versions.)

Includes updates for the `set-output` deprecation as well.

2022-10-27 01:25 UTC, nicklauslittle commented on src/pkgs/vs-buildtools.ps1
> +	$PwrPackageConfig.Version = (Get-VSSetupInstance "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\BuildTools").InstallationVersion.ToString()
Unfortunately, this returns the "Build Version", which is something like `[Major].[Minor].[Date].[Build]`. I have not found a way to get `[Major].[Minor].[Update]`.

2022-10-30 15:02 UTC, troyaf requested changes

2022-10-30 19:05 UTC, nicklauslittle commented on src/pkgs/vs-buildtools.ps1
> +	}
I tweaked this some to use regular expressions, but I should be inline with the code that's listed here.

2022-10-30 19:06 UTC, nicklauslittle commented on src/pkgs/vs-buildtools.ps1
> +	$PwrPackageConfig.UpToDate = -not [SemanticVersion]::new($PwrPackageConfig.Version, '^([0-9]+)\.([0-9]+)\.([0-9]+)(\.[0-9]+)?$').LaterThan($PwrPackageConfig.Latest)
I got rid of the extra version pattern, but moved it up further in the file, since we should know the version before trying to download and install everything now.

2022-10-30 19:07 UTC, nicklauslittle commented on src/pkgs/vs-buildtools.ps1
> +	$PwrPackageConfig.Version = (Get-VSSetupInstance "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\BuildTools").InstallationVersion.ToString()
Moved this further up.

2022-10-31 00:04 UTC, nicklauslittle commented on src/pkgs/vs-buildtools.ps1
> +		if ($_ -match '(?s)<tr.*>(17\.[0-9]*[02468]\.[0-9]+)</.+ href="([^"]+/vs_BuildTools\.exe)"') {
For this regex, I used the information at <https://learn.microsoft.com/en-us/visualstudio/productinfo/release-rhythm> which states that even numbered minor releases are LTSC releases. If we wanted to, we could change this to the following to isolate just the LTSC-labeled releases (assuming they are all labeled this way in the future):

```suggestion
		if ($_ -match '(?s)<tr.*LTSC .*>(17\.[0-9]+\.[0-9]+)</.+ href="([^"]+/vs_BuildTools\.exe)"') {
```

Or even the following, if we want to find other major versions (e.g., `18.0.0`) (Although, I'm guessing the URI would change in that instance):

```suggestion
		if ($_ -match '(?s)<tr.*LTSC .*>([0-9]+\.[0-9]+\.[0-9]+)</.+ href="([^"]+/vs_BuildTools\.exe)"') {
```

I don't have a strong preference towards any of these. If you favor one, then let me know.

2022-11-02 12:07 UTC, troyaf approved these changes

2022-11-02 12:08 UTC, merged