Add rust
airpwr/shipyard pull request #57
Opened 2023-01-30 18:13 UTC by tbateson

2024-09-30 12:03 UTC, tbateson commented on src/main.ps1
> +	}
I added this code because the exit code from robocopy in `Install-PwrPackage` was failing the pipeline. It was not showing the failure in the pipeline until after `Test-PwrPackageInstall` completed, and the whole thing was quite disorienting. Remove if you think it doesn't make sense.

2024-10-04 14:41 UTC, troyaf requested changes
Given your issues with robocopy, I tested with a commit that set the home variables to install directly into our package folder. Seems to work just as well. Let me know if you want to keep this, otherwise I would be okay with reverting.

2024-10-06 04:12 UTC, tbateson commented on src/main.ps1
> +		docker history image --no-trunc
```suggestion
```

2024-10-06 04:12 UTC, tbateson commented on src/pkgs/rust.ps1
> +	foreach ($target in @('x86_64-pc-windows-msvc', 'x86_64-pc-windows-gnu', 'i686-pc-windows-msvc', 'i686-pc-windows-gnu')) {
```suggestion
	foreach ($target in @('x86_64-pc-windows-msvc')) {
```

2024-10-06 04:12 UTC, tbateson commented on src/pkgs/rust.ps1
> +		Get-ChildItem $env:RUSTUP_HOME
```suggestion
```

2024-10-06 04:12 UTC, tbateson commented on src/pkgs/vs-buildtools.ps1
>  }
```suggestion
}

```

2024-10-06 04:43 UTC, tbateson commented
> Given your issues with robocopy, I tested with a commit that set the home variables to install directly into our package folder. Seems to work just as well. Let me know if you want to keep this, otherwise I would be okay with reverting.

Your changes look fine. I removed all of the targets except for the default 64-bit msvc target, as that's the rust-recommended one to use. If anyone wants gnu or 32-bit they can add it themself. This reduced the compressed file size from 330MB to 220MB.

I added a printout to display the gzipped size of the pkg directory to give a general ballpack size of the package. It's more useful for when we're adding new packages, if you know how to only run it for non-scheduled builds that would be the only time we need to see it. Otherwise I don't see significant performance issues with it running.

2024-10-06 21:53 UTC, troyaf approved these changes

2024-10-06 22:01 UTC, troyaf approved these changes

2024-10-06 22:02 UTC, merged